In [858]:
import pandas as pd

In [859]:
df = pd.read_csv('./Awesome Chocolates.xlsx - Data.csv')

In [860]:
df.head(15)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Awesome Chocolates,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,Sales Person,Geography,Product,Date,Amount,Boxes
10,NaN,NaN,Dennison Crosswaite,UK,Almond Choco,1/1/2021,"$2,037",422
11,NaN,NaN,Kelci Walkden,India,Almond Choco,1/1/2021,"$6,160",126
12,NaN,NaN,Gigi Bohling,Canada,Caramel Stuffed Bars,1/1/2021,"$1,442",200
13,NaN,NaN,Madelene Upcott,India,Eclairs,1/1/2021,"$6,979",252
14,NaN,NaN,Oby Sorrel,USA,Manuka Honey Choco,1/1/2021,$966,71

In [861]:
# df = df.loc[df.first_valid_index():]     ## row's delete 
df = df.dropna(axis=0, how='all')  

# df = df.loc[:, df.notna().any()]       ## column's delete
df = df.dropna(axis=1, how='all')

In [862]:
df

,Unnamed: 2,Unnamed: 3,Awesome Chocolates,Unnamed: 5,Unnamed: 6,Unnamed: 7
9,Sales Person,Geography,Product,Date,Amount,Boxes
10,Dennison Crosswaite,UK,Almond Choco,1/1/2021,"$2,037",422
11,Kelci Walkden,India,Almond Choco,1/1/2021,"$6,160",126
12,Gigi Bohling,Canada,Caramel Stuffed Bars,1/1/2021,"$1,442",200
13,Madelene Upcott,India,Eclairs,1/1/2021,"$6,979",252
...,...,...,...,...,...,...
9454,Dotty Strutley,Canada,Drinking Coco,3/14/2022,"$3,325",167
9455,Roddy Speechley,Australia,70% Dark Bites,3/9/2022,"$4,900",205
9456,Curtice Advani,USA,85% Dark Bars,3/4/2022,"$8,911",388
9457,Roddy Speechley,UK,70% Dark Bites,3/24/2022,"$1,316",51
9458,Kaine Padly,Canada,Fruit & Nut Bars,3/1/2022,"$4,340",155

In [863]:
header_row = df.first_valid_index()
df.columns = df.loc[header_row]

df

9,Sales Person,Geography,Product,Date,Amount,Boxes
9,Sales Person,Geography,Product,Date,Amount,Boxes
10,Dennison Crosswaite,UK,Almond Choco,1/1/2021,"$2,037",422
11,Kelci Walkden,India,Almond Choco,1/1/2021,"$6,160",126
12,Gigi Bohling,Canada,Caramel Stuffed Bars,1/1/2021,"$1,442",200
13,Madelene Upcott,India,Eclairs,1/1/2021,"$6,979",252
...,...,...,...,...,...,...
9454,Dotty Strutley,Canada,Drinking Coco,3/14/2022,"$3,325",167
9455,Roddy Speechley,Australia,70% Dark Bites,3/9/2022,"$4,900",205
9456,Curtice Advani,USA,85% Dark Bars,3/4/2022,"$8,911",388
9457,Roddy Speechley,UK,70% Dark Bites,3/24/2022,"$1,316",51
9458,Kaine Padly,Canada,Fruit & Nut Bars,3/1/2022,"$4,340",155

In [864]:
df = df.reset_index(drop=True)    ## index reset kiya... 0 se start
df

9,Sales Person,Geography,Product,Date,Amount,Boxes
0,Sales Person,Geography,Product,Date,Amount,Boxes
1,Dennison Crosswaite,UK,Almond Choco,1/1/2021,"$2,037",422
2,Kelci Walkden,India,Almond Choco,1/1/2021,"$6,160",126
3,Gigi Bohling,Canada,Caramel Stuffed Bars,1/1/2021,"$1,442",200
4,Madelene Upcott,India,Eclairs,1/1/2021,"$6,979",252
...,...,...,...,...,...,...
9445,Dotty Strutley,Canada,Drinking Coco,3/14/2022,"$3,325",167
9446,Roddy Speechley,Australia,70% Dark Bites,3/9/2022,"$4,900",205
9447,Curtice Advani,USA,85% Dark Bars,3/4/2022,"$8,911",388
9448,Roddy Speechley,UK,70% Dark Bites,3/24/2022,"$1,316",51
9449,Kaine Padly,Canada,Fruit & Nut Bars,3/1/2022,"$4,340",155

In [865]:
df.columns.name = None  ## header ka index no. delete karta hy
df

,Sales Person,Geography,Product,Date,Amount,Boxes
0,Sales Person,Geography,Product,Date,Amount,Boxes
1,Dennison Crosswaite,UK,Almond Choco,1/1/2021,"$2,037",422
2,Kelci Walkden,India,Almond Choco,1/1/2021,"$6,160",126
3,Gigi Bohling,Canada,Caramel Stuffed Bars,1/1/2021,"$1,442",200
4,Madelene Upcott,India,Eclairs,1/1/2021,"$6,979",252
...,...,...,...,...,...,...
9445,Dotty Strutley,Canada,Drinking Coco,3/14/2022,"$3,325",167
9446,Roddy Speechley,Australia,70% Dark Bites,3/9/2022,"$4,900",205
9447,Curtice Advani,USA,85% Dark Bars,3/4/2022,"$8,911",388
9448,Roddy Speechley,UK,70% Dark Bites,3/24/2022,"$1,316",51
9449,Kaine Padly,Canada,Fruit & Nut Bars,3/1/2022,"$4,340",155

In [866]:
# df = df.iloc[1:]      #method1--- jitna num(jaise 1 type kiya) likhuga utni row hata dega 
df = df.drop(0)         #method2--- ye 0 index wali row delete kr dega 
df

,Sales Person,Geography,Product,Date,Amount,Boxes
1,Dennison Crosswaite,UK,Almond Choco,1/1/2021,"$2,037",422
2,Kelci Walkden,India,Almond Choco,1/1/2021,"$6,160",126
3,Gigi Bohling,Canada,Caramel Stuffed Bars,1/1/2021,"$1,442",200
4,Madelene Upcott,India,Eclairs,1/1/2021,"$6,979",252
5,Oby Sorrel,USA,Manuka Honey Choco,1/1/2021,$966,71
...,...,...,...,...,...,...
9445,Dotty Strutley,Canada,Drinking Coco,3/14/2022,"$3,325",167
9446,Roddy Speechley,Australia,70% Dark Bites,3/9/2022,"$4,900",205
9447,Curtice Advani,USA,85% Dark Bars,3/4/2022,"$8,911",388
9448,Roddy Speechley,UK,70% Dark Bites,3/24/2022,"$1,316",51
9449,Kaine Padly,Canada,Fruit & Nut Bars,3/1/2022,"$4,340",155

In [867]:
df['Date'] = pd.to_datetime(df['Date'],format='mixed')   ## ye tab kam karega jab ek bhi Nun na ho...
df['Date']

df

# df['Date'] = pd.to_datetime(df['Date'], errors='coerce')  ## isme Nun hone pr bhi format change kr dega...
# df['Date']

,Sales Person,Geography,Product,Date,Amount,Boxes
1,Dennison Crosswaite,UK,Almond Choco,2021-01-01,"$2,037",422
2,Kelci Walkden,India,Almond Choco,2021-01-01,"$6,160",126
3,Gigi Bohling,Canada,Caramel Stuffed Bars,2021-01-01,"$1,442",200
4,Madelene Upcott,India,Eclairs,2021-01-01,"$6,979",252
5,Oby Sorrel,USA,Manuka Honey Choco,2021-01-01,$966,71
...,...,...,...,...,...,...
9445,Dotty Strutley,Canada,Drinking Coco,2022-03-14,"$3,325",167
9446,Roddy Speechley,Australia,70% Dark Bites,2022-03-09,"$4,900",205
9447,Curtice Advani,USA,85% Dark Bars,2022-03-04,"$8,911",388
9448,Roddy Speechley,UK,70% Dark Bites,2022-03-24,"$1,316",51
9449,Kaine Padly,Canada,Fruit & Nut Bars,2022-03-01,"$4,340",155

In [869]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9449 entries, 1 to 9449
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sales Person  9449 non-null   str
 1   Geography     9449 non-null   str
 2   Product       9449 non-null   str
 3   Date          9449 non-null   datetime64[us]
 4   Amount        9449 non-null   str
 5   Boxes         9449 non-null   str
dtypes: datetime64[us](1), str(5)
memory usage: 443.1 KB

In [ ]:
# df.to_csv('DummyAwesome.csv', index=False)